<template>
  <v-footer
    height="auto"
    color="primary"
    :fixed="true"
    app
  >
    <v-layout
      justify-center
      row
      wrap
    >
    <v-flex
      primary
      py-3
      text-xs-center
      white--text
      xs12
    >
      &copy;2018 — <strong>Vuetify</strong>
    </v-flex>
    </v-layout>
  </v-footer>
</template>
